# Generated by Django 3.2.6 on 2022-03-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='nombre',
            new_name='name',
        ),
    ]
